# This is a basic workflow to help you get started with Actions

name: Teste Zip

# Controls when the workflow will run
on: workflow_dispatch
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_fronts:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout do Projeto
        uses: actions/checkout@v2
      - name: Upload do Arteafto
        uses: actions/upload-artifact@v2
        with:
          name: artefato
          path: dist
